/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  totem_sidebar: [{type: 'autogenerated', dirName: '.'},
  


    
  ],
  

  


   //should be mapped to docusaurus.config.js -> themeConfig -> sidebarId
   // tutorialSidebar: [
   //
   //  {
   //   type: 'category',
   //   label: 'XYZ', // Label of Menu Root 
   //   items: ['DevTech/Python/Python_Basic_Print', 'DevTech/Python/Python_File'], // 有序 list
   //   
   // },
   // ],
  
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
